---
collections:
  - name: community.kubernetes
    version: "2.0.1"
  - name: operator_sdk.util
    version: "0.5.0"
  - name: kubernetes.core
    version: "5.2.0"
  - name: cloud.common
    version: "4.0.0"
  - community.general
  - community.okd
